apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: organizations-config
    files:
      - config/huisarts-nootenboom.json
      - config/verpleeghuis-de-nootjes.json
      - config/zkh-noot-aan-de-man.json
