apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - volume.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: service-space-config
    files:
      - config/nuts.yaml
