apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-space-working-dir
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
